# Generated by Django 4.2.5 on 2023-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attandance',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('isPresent', models.BooleanField()),
                ('attandence_log', models.JSONField()),
            ],
        ),
    ]
