# Generated by Django 4.2.5 on 2023-10-05 16:15

import backend.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('starting_date', models.DateField()),
                ('num_of_days', models.IntegerField()),
                ('num_of_sessions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('attendence_log', models.JSONField(default=backend.models.defaultDict)),
                ('misc_log', models.JSONField(default=backend.models.defaultDict)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.event')),
            ],
        ),
    ]
