# Generated by Django 4.2.5 on 2023-09-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('isPresent', models.BooleanField()),
                ('attandence_log', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Attandance',
        ),
    ]
