# Generated by Django 4.2.5 on 2023-10-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='id',
        ),
    ]
