# Generated by Django 4.2.5 on 2023-09-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_attendance_delete_attandance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attandence_log',
            field=models.JSONField(null=True),
        ),
    ]
