# Generated by Django 4.2.5 on 2023-09-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_attendance_attandence_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attandence_log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
