# Generated by Django 4.2.5 on 2023-09-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_attendance_attandence_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attandence_log',
            field=models.JSONField(default={'in': 'out'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='isPresent',
            field=models.BooleanField(default=False),
        ),
    ]
