# Generated by Django 4.2.5 on 2023-09-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_attendance_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='Attendence',
        ),
    ]
