# Generated by Django 4.2.5 on 2023-09-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_attendance_attendence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='attandence_log',
            new_name='attendence_log',
        ),
    ]
