# Generated by Django 4.2.5 on 2023-10-03 05:18

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_attendence_attendence_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='isPresent',
        ),
        migrations.AddField(
            model_name='attendence',
            name='misc_log',
            field=models.JSONField(default=backend.models.defaultDict),
        ),
    ]
